### ISSUE TITLE
分位数表是怎么计算的？

### ISSUE THREAD

**Issue by Protostars** [ChuanyuXue/MVTest#1]
我简单看了下论文，统计量的概率密度函数形式大概是N个卡方分布的概率密度函数之和？
请问代码里求p-value的分位数表是如何计算的呢？

**Comment by ChuanyuXue** [comment]
是的，是卡方分布的和。P-value的计算方式请参考论文。

**Comment by Protostars** [comment]
可以给出分位数表的计算程序吗？
